### ISSUE TITLE
Add controllers for birth date input

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/Co-Tidal#10]
Once fixed import the controller code into the processing code if that's where it makes sense

**Comment by GemmaMayLatham** [comment]
Let me know if you want the thermal printer to test this while I'm away

**Comment by cheapjack** [comment]
@GemmaMayLatham that's a good idea: I could pickup from MadLab on Thursday?

**Comment by GemmaMayLatham** [comment]
would make sense. I'll leave it with the laser stuff

**Comment by cheapjack** [comment]
![rotarynumberdialreader](https://cloud.githubusercontent.com/assets/128456/17387223/8a35ae70-59e9-11e6-8f54-024469296884.png)

I've made a test bit of [code](https://github.com/cheapjack/Co-Tidal/blob/master/DialHack.ino) to read this RS number dial switch. Will need to use a MEGA to read I _think_ 19 digital pins so  we can input birth months and years and send over serial to the processing sketch and then onto the thermal printers. Might need some help from @amcewen for that bit...

**Comment by cheapjack** [comment]
Will work on boxing & soldering them & arduino MEGA up so they're easy to use: might be nice to design so it sits around one of the printers; will have a think once Ive got everything in DoES on Friday

**Comment by GemmaMayLatham** [comment]
Box thermal printer is in is tiny, feel free to move to a combined one, will look nice I think. Still bring the original box though please

**Comment by amcewen** [comment]
I've got an Arduino Mega we can use for it.  Have been working on how to choose the month - have a 3d-printed and laser-cut cylinder design that'll work with a potentiometer.
