### ISSUE TITLE
Order/Source any outstanding Components

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/Co-Tidal#12]
- [ ] Laser Cut Material
- [ ] Box making for thermal printer?
- [x] Keyrings
- [ ] Necklace chains?
- [ ] Tidal Buoy components to work on:
  - [x] Water gun for peristaltic motor (on order)

**Comment by GemmaMayLatham** [comment]
I've ordered key rings (100) and have a little box for one printer. Might be nice to have box for the main printer plus input dials?

**Comment by amcewen** [comment]
I've got an arcade button on order, so hopefully we'll be able to use that plus the dials for the calendar input.
