### ISSUE TITLE
Write up the workshop plan

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/Co-Tidal#13]

**Comment by GemmaMayLatham** [comment]
From Amanda's schedule looks like 12-4 each day and on a drop in basis

**Comment by cheapjack** [comment]
## Workshop Plan

_Workshop running 12-4 may have to extend this as museum opens at 10_
- Man printer and explain process
- Input birth date and print
- Help select needle and thread, explain risks
- Help with sewing and talk about tides

## Background
- Improve how the data modifys the image
- Source a more Oslo based pattern
- Blog about the stories
- Hack the peristaltic motor with Elizabeth's water
