### ISSUE TITLE
develop code to send coded pattern via radio module to main printer

### ISSUE THREAD

**Issue by GemmaMayLatham** [cheapjack/Co-Tidal#14]

**Comment by GemmaMayLatham** [comment]
-might be able to just plug 2 into one arduino

**Comment by GemmaMayLatham** [comment]
This may bit a bit faffy. Wondering if we can just get the main code to talk yo two printers at once via two serial ports. Thoughts?

**Comment by amcewen** [comment]
That should be pretty easy to do.  I've got a 5m USB extension cable I can bring if that will let us site one of the printers in a more interesting position

**Comment by GemmaMayLatham** [comment]
Great! Can you test with your printer and mine when ross has picked it up? I have a second printer with me if we need that.

**Comment by amcewen** [comment]
Yep, will do.  Haven't got our printer up and running yet but will look at it after lunch

**Comment by amcewen** [comment]
The printer works.  And it's got a paper cutter!  Next step is hooking it up to @GemmaMayLatham's Processing code...

**Comment by GemmaMayLatham** [comment]
Yay!...and ooooh a cutter. Perhaps would be good to use that one for the printouts to follow for stitching so people can take their own easily

**Comment by cheapjack** [comment]
👍

**Comment by amcewen** [comment]
Version checked in with commit https://github.com/cheapjack/Co-Tidal/commit/3463a9f86f95392a703425e1a0dd1ce3b10f247c has both a cutting command and controls a second printer also plugged in via USB.
