### ISSUE TITLE
Write Code to translate the tide heights from the JSON to a new output string ready for printing

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/Co-Tidal#15]
@gemmamaylatham. Can we work on how we let the JSON change the OUTPUT.TXT strings so we end up with different patterns for each birth date

**Comment by GemmaMayLatham** [comment]
Had uploded file to do this but it want in a folder. Have just re-added full folder - Tide_Pattern that takes JSON And interacts with pattern.  File includes couple of options for original pattern too. Think folakart2 looks best

**Comment by cheapjack** [comment]
@GemmaMayLatham can’t see how the data float object from the JSON in 

```
float data = TideHeight.getFloat("height");//get value of height from   it
    println(data);
```

Actually does anything to the loaded image in `input`

The code just reads it, scales it, turns to black and white with `PImage(THRESHOLD);` and then into a string for printing but doesn’t do anything else unless Im missing something?

Or is that the bit we said we’d work on? Think it might be ;)

**Comment by cheapjack** [comment]
@GemmaMayLatham  definately doesn't do anything with `TideHeight` it's ok we can look at it we've got 6 hours 👍

**Comment by GemmaMayLatham** [comment]
Bit that's annoying because it did do something!!! You shouldn't need to do anything other that combine to dial inputs!!

Can you send me pictures please

**Comment by GemmaMayLatham** [comment]
Have you compared the output image against the folkart2.jpg?

**Comment by GemmaMayLatham** [comment]
Have you plugged it into the printer?

**Comment by GemmaMayLatham** [comment]
@cheapjack please send me a pic before I board plane

**Comment by cheapjack** [comment]
This is the OUTPUT.txt using folkart2.jpg                    

```
        ))))            
       )))))            
      ))))))            
      ))))))            
      )))))             
   )) ))))    ))))      
  )))) ))       )))     
  )))  )    ))) )))     
  ))) ))   )))) )))     
   )) ))   )))) )))     
   ))  ) ) )))  ))      
    )) ) )) )))) )))))  
      )  )) ))))) ))))  
         )) ))))) ))))  
     )   )) ))))) ))))  
    )) ) )) )))  ))))   
   )) ))   )))  ))      
  ))) ))   )))) )))     
  ))) ))   )))) )))     
  )))  )    ))) )))     
  )))) ))      ))))     
   )) ))))     ))       
      )))))             
      ))))))            
      ))))))            
       )))))            
        )))             


```

**Comment by cheapjack** [comment]
Prototype code up and running...

**Comment by cheapjack** [comment]
Sorry @gemmamaylatham didn't get your message until too late but we've got a little system going that's working for opening and we can work on while we here :)

**Comment by amcewen** [comment]
Fixed with the code checked in for commit https://github.com/cheapjack/Co-Tidal/commit/3463a9f86f95392a703425e1a0dd1ce3b10f247c
