### ISSUE TITLE
Compile Accomodation & Travel Details

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/Co-Tidal#4]

**Comment by GemmaMayLatham** [comment]
also check transport to from both airports

**Comment by cheapjack** [comment]
[Oslo Rygge Airport transfer to Oslo](http://www.visitoslo.com/en/transport/transport-airport/moss-rygge/) (Gemma)
[Oslo Torp Airport transfer to Oslo](http://www.visitoslo.com/en/transport/transport-airport/sandefjord-torp/) (Ross/Adrian) Ross is better on train, bus bit of a nightmare to climb steps :)

**Comment by cheapjack** [comment]
@GemmaMayLatham can you let me know when your flight gets in on the Wednesday then I can time/work out an ETA for you or see if anyone can meet you?

**Comment by GemmaMayLatham** [comment]
get in at 16:10

**Comment by cheapjack** [comment]
Think we all know where we are going now
