### ISSUE TITLE
Laser cutting

### ISSUE THREAD

**Issue by GemmaMayLatham** [cheapjack/Co-Tidal#8]
Laser cut acrylic and wood - Ross can you collect scraps from MadLab on Thursday still? I will parcel up and let staff know you are coming in. I have cut some today but MadLab laser cutter is now out of action :(

**Comment by cheapjack** [comment]
Yes my meeting at MOSI is at 1 so should be over at madlab by 4/5 can you just leave it somewhere with no stairs? Or are you leaving it with James or someone ta!

**Comment by GemmaMayLatham** [comment]
Yes, I'll leave it downstairs and makesure someone comes down to show you where it is. If you buzz the office they will let you in. James is in Dundee this week. Will try and confirm who will be in the office for you.  If you will be in the car you can pull up in the loading bay directly outside.

**Comment by cheapjack** [comment]
Great I've booked in Friday 5th to cut on the DoES cutter :)

**Comment by GemmaMayLatham** [comment]
I may well be back from hull by 4/5 but will leave with someone just in case

**Comment by cheapjack** [comment]
So if you think of anything else that might need cutting or case making let me know and break it put into another issue :)

**Comment by GemmaMayLatham** [comment]
will do :)

**Comment by GemmaMayLatham** [comment]
Two slim kitronik boxes with acrylic and wood offcuts have been left at MadLab leaning against the laser cutter in the Hackspace with your name in big letters. The thermal printer and some till rolls are in a white envelope in front on these. Doya in the office is expecting you tomorrow. Buzz the office when you get there and she will come down and help you find the bits.  call me before you head over though in case I'm about

**Comment by cheapjack** [comment]
👍
